<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>testJS</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-06-13T17:55:13</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b6979b1d-7b8c-4e01-8d93-d869ca325d26</testSuiteGuid>
   <testCaseLink>
      <guid>2899469c-5a25-4f5e-ba91-d20b60698888</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OpenBrowser</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>09bbc470-c45a-4c2b-bc48-ad341e4d1baa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a137b6df-1680-4dbf-823a-3a15cd3a1231</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de60f2bf-8869-4f2a-a95f-e9ad07d8a886</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c13e1b8-80e2-4f3e-bedb-6ca89950774f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4808d927-6c3d-40e2-abfd-87b332dd5580</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/test</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
