<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>first_arrow_xnode</name>
   <tag></tag>
   <elementGuidId>84c2dd21-bf20-4669-bcd1-0b2337a43290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody[starts-with(@id,&quot;treeview&quot;)]/tr[1]//img[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody[starts-with(@id,&quot;treeview&quot;)]/tr[1]//img[1]</value>
   </webElementProperties>
</WebElementEntity>
