<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_peerlist_pause</name>
   <tag></tag>
   <elementGuidId>6d8707cb-b22d-4df0-9982-29388513069e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@class,&quot;kt_peerlist_pause&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@class,&quot;kt_peerlist_pause&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
