<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_server_pause</name>
   <tag></tag>
   <elementGuidId>b7ae3e85-d13f-413c-b1d7-6eaaa231af68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[contains(@class,&quot;kt_serverpeer_btn_start&quot;)])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[contains(@class,&quot;kt_serverpeer_btn_start&quot;)])[1]</value>
   </webElementProperties>
</WebElementEntity>
