<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_peerlist_play</name>
   <tag></tag>
   <elementGuidId>e430b315-d61d-42f3-9aea-b87154c73f3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@class,&quot;kt_peerlist_play&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@class,&quot;kt_peerlist_play&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
