<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_server_restart</name>
   <tag></tag>
   <elementGuidId>4c7f364c-34b1-4cde-a021-a14eb9dc3e26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[contains(@class,&quot;kt_serverpeer_restart&quot;)])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[contains(@class,&quot;kt_serverpeer_restart&quot;)])[1]</value>
   </webElementProperties>
</WebElementEntity>
