<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_server_start</name>
   <tag></tag>
   <elementGuidId>565cee07-42d7-4761-8033-df082e9dfce2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[contains(@class,&quot;kt_serverpeer_btn_start&quot;)])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[contains(@class,&quot;kt_serverpeer_btn_start&quot;)])[1]</value>
   </webElementProperties>
</WebElementEntity>
