<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>serverpeer_protocol</name>
   <tag></tag>
   <elementGuidId>04bdcd9f-046b-4cb7-8c3a-648781da9198</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,&quot;kt_serverpeer_protocol&quot;)])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,&quot;kt_serverpeer_protocol&quot;)])[1]</value>
   </webElementProperties>
</WebElementEntity>
