<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>msg_servername</name>
   <tag></tag>
   <elementGuidId>cd8e5de6-e0bb-472c-b93d-e26b7ecf301e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@class,&quot;kt_msg_servername&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(@class,&quot;kt_msg_servername&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
