<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kt_view_dataentry_spazio_list_container_btn_clearicon</name>
   <tag></tag>
   <elementGuidId>94d7fa9a-622d-4a9a-a9d7-34ec4dd75773</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kt_view_dataentry_spazio_list_container_btn_clearicon</value>
   </webElementProperties>
</WebElementEntity>
