<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kt_view_dataentry_spazio_list_container</name>
   <tag></tag>
   <elementGuidId>047159f2-84fb-490a-adad-566cba7ab89e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kt_view_dataentry_spazio_list_container</value>
   </webElementProperties>
</WebElementEntity>
